### ISSUE TITLE
All hover effect

### ISSUE THREAD

**Issue by TonyQ032** [PreDevz/Platello#22]
When the user hovers over a link it should turn to the dark blue PreDevs color. At the moment this only works when initially loading the page. If the user decides to switch between day and night mode then this effect breaks. 

The link hovering should still work regardless of theme being used.

**Comment by TDGNate** [comment]
we can possibly do something like this https://stackoverflow.com/questions/24629531/hover-effect-disappear-after-calling-function-through-button

**Comment by TDGNate** [comment]
Oh shoot and it is also affecting the title "Platello"
after switching themes, the hover for that doesn't work either
